mqtt:
  hostname: 192.168.8.85
  port: 1883
  user: mqttjuanma
  password: xxxxxxx
deviceName: proxmox
client_id: proxmox
timezone: Europe/Madrid
update_interval: 60
check_wifi_strength: false
check_available_updates: false
